### ISSUE TITLE
Share cat's picture

### ISSUE THREAD

**Issue by OjVaGab** [NeuroHackademy2024/geometry#17]
@hughesdy , please share your cat's picture ASAP

**Comment by emmajanecorley** [comment]
![IMG_3978](https://github.com/user-attachments/assets/cadea495-2e37-4284-bd94-0e1d51a9d423)

**Comment by emmajanecorley** [comment]
https://github.com/user-attachments/assets/f2150cdc-960b-459d-885a-307735841644

**Comment by emmajanecorley** [comment]
![IMG_1978](https://github.com/user-attachments/assets/055bbfc7-a0f0-415b-a6c1-8218a2aa6150)

**Comment by emmajanecorley** [comment]
![Uploading IMG_2594.jpeg…]()

**Comment by emmajanecorley** [comment]
https://github.com/user-attachments/assets/a252658e-dfb2-4b0f-afd1-fd7bd1bc8def

**Comment by emmajanecorley** [comment]
https://github.com/user-attachments/assets/318ce116-cbb1-4273-a35b-91365f1e9f86

**Comment by emmajanecorley** [comment]
![b5f31a2b-ea44-423f-9d33-a3db673920c8](https://github.com/user-attachments/assets/b8be6dcf-5412-4fa9-a035-49e949495bf9)

**Comment by smwong4** [comment]
![IMG_8004](https://github.com/user-attachments/assets/20753d53-b54e-49a3-85da-a3def3b772f3)
